services:
  easychat:
    build:
      context: .
      dockerfile: Dockerfile
    image: easychat:latest
    container_name: easychat
    ports:
      - "7777:7777"
    environment:
      EASYCHAT_ADMIN_PASSWORD: change-this-password
      LOG_PATH: /app/server/logs/easychat.log
    restart: unless-stopped
    volumes:
      - ./server/presets.json:/app/server/presets.json
      - ./server/logs:/app/server/logs
      - ./server/uploads:/app/server/uploads
